Repository blackberggroup/VA-DOE, pull requests merged in 2024-03, with the labels that each got.

#34 Feature 6156040636 webpage updates
  _includes/home/doe-team.html
  _includes/sharktank/3-up.html
  _site/assets/img/.DS_Store
  _site/assets/img/diffusion-practices/card4.jpg
  _site/assets/img/diffusion-practices/card5.jpg
  _site/assets/img/diffusion-practices/card6.jpg
  _site/assets/img/diffusion-practices/card7.jpg
  _site/assets/img/home/news_8.jpg
  _site/assets/img/home/news_9.jpg
  _site/assets/img/home/row5.jpg
  _site/assets/img/home/team-fitzgerald.png
  _site/assets/img/home/team-goetschius.png
  _site/assets/img/home/team-hagan.png
  _site/assets/img/home/team-henderson.png
  _site/assets/img/home/team-mccoy.png
  _site/assets/img/sharktank/contraception-on-demand.jpg
  _site/assets/img/sharktank/research.jpg
  _site/assets/img/sharktank/sharktank-finals-revealed.jpg
  _site/assets/img/sharktank/st.jpg
  _site/assets/img/sharktank/vha-sharktank.jpg
  _site/assets/img/sharktank/white-noise-project.jpg
  _site/assets/js/doe-news.js
  _site/assets/js/practices-news.js
  _site/assets/js/sharktank-news.js
  _site/sharktank/index.html
  assets/img/diffusion-practices/card4.jpg
  assets/img/diffusion-practices/card5.jpg
  assets/img/diffusion-practices/card6.jpg
  assets/img/diffusion-practices/card7.jpg
  assets/img/home/news_8.jpg
  assets/img/home/news_9.jpg
  assets/img/home/row5.jpg
  assets/img/home/team-fitzgerald.png
  assets/img/home/team-goetschius.png
  assets/img/home/team-hagan.png
  assets/img/home/team-henderson.png
  assets/img/home/team-mccoy.png
  assets/img/sharktank/contraception-on-demand.jpg
  assets/img/sharktank/research.jpg
  assets/img/sharktank/sharktank-finals-revealed.jpg
  assets/img/sharktank/st.jpg
  assets/img/sharktank/vha-sharktank.jpg
  assets/img/sharktank/white-noise-project.jpg
  assets/js/doe-news.js
  assets/js/practices-news.js
  assets/js/sharktank-news.js
Labels: image compression, ready for review

#36 Fix 6237634837 font sizing/element display issues
  _site/assets/css/styles.css
  _site/assets/js/doe-news.js
  _site/assets/js/sharktank-news.js
  _site/assets/sass/vha/pages/home/news/_index.scss
  _site/assets/sass/vha/pages/home/programs/_index.scss
  assets/css/styles.css
  assets/js/doe-news.js
  assets/js/sharktank-news.js
  assets/sass/vha/pages/home/news/_index.scss
  assets/sass/vha/pages/home/programs/_index.scss
Labels: ready for review

#37 Bugfix/jls 6158463071/update email
  .github/workflows/deploy-dev-sandbox.yml
  _includes/talent-accelerator/recruitment.html
  _site/assets/js/doe-news.js
  _site/diffusion-talent-accelerator/index.html
Labels: bug, ready for review

#38 Feature/jls 6158463071/dta client content changes
  _includes/talent-accelerator/dta-syllabus.html
  _includes/talent-accelerator/impact.html
  _includes/talent-accelerator/mission.html
  _includes/talent-accelerator/timeline.html
  _site/assets/css/styles.css
  _site/assets/js/mustache-fellows-render.js
  _site/assets/sass/vha/pages/talent-accelerator/mission/_index.scss
  _site/assets/sass/vha/pages/talent-accelerator/timeline/_index.scss
  _site/diffusion-talent-accelerator/index.html
  assets/css/styles.css
  assets/js/mustache-fellows-render.js
  assets/sass/vha/pages/talent-accelerator/mission/_index.scss
  assets/sass/vha/pages/talent-accelerator/timeline/_index.scss
Labels: enhancement, ready for review

#39 bug: add z-index to syllabus; add space after colon; edit 2nd bullet
  _includes/talent-accelerator/dta-syllabus.html
  _includes/talent-accelerator/timeline.html
  _site/assets/js/mustache-fellows-render.js
  _site/diffusion-talent-accelerator/index.html
  assets/js/mustache-fellows-render.js
Labels: bug, enhancement, ready for review

#40 feat: update mindys title
  _site/assets/js/mustache-fellows-render.js
  assets/js/mustache-fellows-render.js
Labels: enhancement, ready for review

#41 feat: add drhci to nav
  _includes/header-sub.html
  _includes/header.html
  _site/diffusion-talent-accelerator/index.html
  _site/index.html
  _site/national-diffusion-practices/index.html
  _site/sharktank/index.html
Labels: enhancement, ready for review
